/**
 * Encodes the app icons (src/web/app-icon.ts) as PNG into src/web/app-icons.generated.ts, which the Worker
 * serves at /icons/<name>.png. Run after changing the drawing; a test fails until you do.
 *
 *   bun apps/worker/scripts/icons.ts
 */
import { deflateSync } from "node:zlib";
import { APP_ICONS, drawIcon } from "../src/web/app-icon";

const CRC = new Uint32Array(256).map((_, n) => {
  let c = n;
  for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
  return c >>> 0;
});
function crc32(bytes: Uint8Array): number {
  let c = 0xffffffff;
  for (const b of bytes) c = (CRC[(c ^ b) & 0xff] as number) ^ (c >>> 8);
  return (c ^ 0xffffffff) >>> 0;
}

function chunk(type: string, data: Uint8Array): Uint8Array {
  const out = new Uint8Array(12 + data.length);
  const view = new DataView(out.buffer);
  view.setUint32(0, data.length);
  out.set(new TextEncoder().encode(type), 4);
  out.set(data, 8);
  view.setUint32(8 + data.length, crc32(out.subarray(4, 8 + data.length)));
  return out;
}

export function encodePng(size: number, rgba: Uint8Array): Uint8Array {
  const header = new Uint8Array(13);
  const h = new DataView(header.buffer);
  h.setUint32(0, size);
  h.setUint32(4, size);
  header.set([8, 6, 0, 0, 0], 8); // 8-bit RGBA, no interlace
  // Each row starts with filter type 0 (none).
  const raw = new Uint8Array(size * (size * 4 + 1));
  for (let y = 0; y < size; y++) {
    raw.set(rgba.subarray(y * size * 4, (y + 1) * size * 4), y * (size * 4 + 1) + 1);
  }
  const parts = [
    new Uint8Array([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", header),
    chunk("IDAT", new Uint8Array(deflateSync(raw, { level: 9 }))),
    chunk("IEND", new Uint8Array(0)),
  ];
  const png = new Uint8Array(parts.reduce((n, p) => n + p.length, 0));
  let at = 0;
  for (const p of parts) {
    png.set(p, at);
    at += p.length;
  }
  return png;
}

if (import.meta.main) {
  const lines = APP_ICONS.map(({ name, size, maskable }) => {
    const b64 = Buffer.from(encodePng(size, drawIcon(size, maskable))).toString("base64");
    return `  "${name}": "${b64}",`;
  });
  const out = `// Generated by apps/worker/scripts/icons.ts from app-icon.ts. Do not edit: run the script.
/** The app icons as base64 PNG, by the name in their address (/icons/<name>.png). */
export const APP_ICON_PNG: Record<string, string> = {
${lines.join("\n")}
};
`;
  const path = new URL("../src/web/app-icons.generated.ts", import.meta.url).pathname;
  await Bun.write(path, out);
  console.log(`wrote ${path} (${out.length} bytes)`);
}
