/**
 * Renders the link-preview card (scripts/share-card.html) to a 1200x630 PNG with headless Chrome and
 * writes it into src/web/share-card.generated.ts, which the Worker serves at /share-card.png. The
 * Worker serves bytes and never draws, exactly as with the app icons (scripts/icons.ts).
 *
 *   bun apps/worker/scripts/share-card.ts
 *
 * CHROME overrides the browser path (default: the macOS Google Chrome install).
 */
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { SHARE_CARD_HEIGHT, SHARE_CARD_WIDTH } from "../src/web/share-card";

const chrome = process.env.CHROME ?? "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const html = new URL("./share-card.html", import.meta.url).pathname;
const work = mkdtempSync(join(tmpdir(), "share-card-"));
const png = join(work, "card.png");

try {
  const run = Bun.spawnSync([
    chrome,
    "--headless=new",
    "--disable-gpu",
    "--hide-scrollbars",
    "--force-device-scale-factor=1",
    `--window-size=${SHARE_CARD_WIDTH},${SHARE_CARD_HEIGHT}`,
    `--user-data-dir=${join(work, "profile")}`,
    `--screenshot=${png}`,
    `file://${html}`,
  ]);
  if (run.exitCode !== 0)
    throw new Error(`chrome exited ${run.exitCode}: ${run.stderr.toString()}`);
  const bytes = readFileSync(png);
  // A wrong window size would ship a card Facebook crops; check the PNG header rather than trust it.
  const width = bytes.readUInt32BE(16);
  const height = bytes.readUInt32BE(20);
  if (width !== SHARE_CARD_WIDTH || height !== SHARE_CARD_HEIGHT) {
    throw new Error(`rendered ${width}x${height}, want ${SHARE_CARD_WIDTH}x${SHARE_CARD_HEIGHT}`);
  }
  const out = `// Generated by apps/worker/scripts/share-card.ts from share-card.html. Do not edit: run the script.
/** The link-preview card as base64 PNG, served at /share-card.png. */
export const SHARE_CARD_PNG =
  "${bytes.toString("base64")}";
`;
  const path = new URL("../src/web/share-card.generated.ts", import.meta.url).pathname;
  await Bun.write(path, out);
  console.log(`wrote ${path} (${bytes.length} byte PNG)`);
} finally {
  rmSync(work, { recursive: true, force: true });
}
